### ISSUE TITLE
Hostname Api configuration

### ISSUE THREAD

**Issue by crosstomation** [Highwinds/CDNWS-examples#3]
Hi, 
1. Can you please provide an example for setting hostname for a given host?
    in old API we used virtualhosts, is there any equivalent? 
2. Can you please provide an example for creating a new host?

**Comment by thinkjson** [comment]
There is an existing example on provisioning a host: https://github.com/Highwinds/CDNWS-examples/blob/master/provision_host/provision_host.py

I'll alter this example to create a hostname at CDS root as well.
